### ISSUE TITLE
Scala Meetup @ Beijing #1 议题

### ISSUE THREAD

**Issue by He-Pin** [scalacn/scala-meetup#1]
请各位参见者在本条信息中评论自己可能感兴趣的或者准备交流的 Topic，
最后由本次会议的组织者 @Hawstein 统一协调。

建议模式：
- 每个 Topic 5 分钟左右的描述，随后是问答阶段。

该 Topic 最后由 @Hawstein 更新和总结。

**Comment by HugeNature** [comment]
mark

**Comment by He-Pin** [comment]
本次我可以交流的有：
- Akka 在手机游戏服务器中的应用。
- Scala 和 Java 8 的混合多模块工程。

**Comment by Hawstein** [comment]
我的：
- 使用 Akka Streams 搭建实时日志分析服务。
- Akka 在后端服务中的应用。

**Comment by He-Pin** [comment]
更新会议信息：
时间：2016.01.17 周日 14:00 - 17:00

地点：北京市海淀区中关村善缘街 1 号立方庭大厦 1 楼科苑星空咖啡厅

百度地图：（http://j.map.baidu.com/51mg8）

**Comment by He-Pin** [comment]
活动已经顺利完结：

![cy66tf8wyae0fl9](https://cloud.githubusercontent.com/assets/501740/12428996/dbe3fcd4-bf22-11e5-99ae-b0ca91748598.jpg)

Scala Meetup @北京 #1 [回顾](https://github.com/scalacn/scala-meetup/blob/master/Beijing/2016-01-17%231.md)

**Comment by liangqing** [comment]
你们是通过邮件列表还是其他方式组织的呢？怎样加入？
